injectEnvironmentFiles:
  - .env.local?

enableGlobalCache: false

npmScopes:
  imrevanschaijk:
    npmAlwaysAuth: true
    npmAuthToken: "${GH_TOKEN:-fallback}"
    npmRegistryServer: "https://npm.pkg.github.com/"
